services:
  app-postgres:
    container_name: app-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5436:5432"
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: db_um_test
    networks:
      - app_network_test

networks:
  app_network_test:
    driver: bridge