services:
  app-postgres:
    container_name: app-postgres
    image: postgres:16-alpine
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_um
    networks:
      - app_network

  app-api:
    container_name: app-api
    restart: always
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - app-postgres
    networks:
      - app_network

  # app-web:
  #  build: ./web
  #  container_name: app-web
  #  restart: always
  #  ports:
  #    - "85:80"
  #  depends_on:
  #    - app-api
  #  networks:
  #    - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres-data:
    driver: local